/**
 * beatstars.ts
 *
 * Featured beats for the homepage Beat Store row.
 * Pulls live from our local catalog (data/beats.ts) — auto-generated by
 * _build_beats_catalog.py from BRMG/Production/MASTERED BEATS.
 *
 * Selection is deterministic: one paid beat per major style (East Coast,
 * West Coast, Trap) — the first one we find with that prefix. Re-running
 * the catalog builder rotates whatever's at the front.
 */

import { BEATS } from "@/data/beats";

export type Beat = {
  id: string;
  name: string;
  bpm: number;
  style: string;
  priceUSD: number;
  licenseLabel: string;
  previewUrl?: string;
  buyUrl?: string;
};

const CATEGORY_PREFIXES = ["trap-", "east-coast-", "west-coast-"] as const;

const FALLBACK: Beat[] = [
  { id: "fallback-trap",  name: "Loading…",  bpm: 0, style: "Trap",       priceUSD: 29.99, licenseLabel: "Lease · MP3 + WAV", buyUrl: "/beats" },
  { id: "fallback-east",  name: "Loading…",  bpm: 0, style: "East Coast", priceUSD: 29.99, licenseLabel: "Lease · MP3 + WAV", buyUrl: "/beats" },
  { id: "fallback-west",  name: "Loading…",  bpm: 0, style: "West Coast", priceUSD: 29.99, licenseLabel: "Lease · MP3 + WAV", buyUrl: "/beats" },
];

export async function fetchFeaturedBeats(): Promise<Beat[]> {
  const paid = BEATS.filter((b) => !b.isFree);
  const featured: Beat[] = [];
  for (const prefix of CATEGORY_PREFIXES) {
    const match = paid.find((b) => b.slug.startsWith(prefix));
    if (!match) continue;
    featured.push({
      id: match.slug,
      name: match.title,
      bpm: match.bpm ?? 0,
      style: match.categoryLabel,
      priceUSD: match.priceUSD,
      licenseLabel: "Lease · MP3 + WAV",
      previewUrl: match.previewUrl,
      buyUrl: `/beats/${match.slug}`,
    });
  }
  return featured.length === 3 ? featured : FALLBACK;
}
