import Header from "@/components/Header";
import TikTokFeed from "@/components/TikTokFeed";
import ShowEmbed from "@/components/ShowEmbed";
import SubstackSticker from "@/components/SubstackSticker";
import Footer from "@/components/Footer";
import {
  OnAirBar,
  RoomHero,
  ProgramGuide,
  BeatLabV3,
  MerchZone,
  GirlsZone,
  AdBreak,
} from "@/components/HomeV3";
import { SOCIAL } from "@/data/social";
import Link from "next/link";
import { getLiveEssays } from "@/data/lane-essays";

// Use `title.absolute` so the layout's "%s — Sneakz & Beatz" template doesn't
// append a duplicate brand suffix to the homepage title.
export const metadata = {
  title: {
    absolute:
      "Sneakz & Beatz — Sneakers, Hip-Hop, Anime, Gaming. Black-owned culture brand.",
  },
  description:
    "Sneakz & Beatz is the editorial home for sneakerheads who live hip-hop, anime, and gaming. The PHRHX Show, 100 mastered beats, the $79 Vault, the $10K Rap Challenge.",
  alternates: { canonical: "https://www.sneakzandbeatz.com" },
  openGraph: {
    title: "Sneakz & Beatz — Sneakers, Hip-Hop, Anime, Gaming",
    description:
      "Black-owned culture brand for sneakerheads who live hip-hop, anime, and gaming. Watch The PHRHX Show, get 100 mastered beats in the $79 Vault, win $10K in the Rap Challenge.",
    url: "https://www.sneakzandbeatz.com",
    siteName: "Sneakz & Beatz",
    type: "website",
    // images omitted — file-based src/app/opengraph-image.tsx generates a
    // custom homepage OG card. Twitter inherits the same image.
  },
  twitter: {
    card: "summary_large_image",
    title: "Sneakz & Beatz — Sneakers, Hip-Hop, Anime, Gaming",
    description:
      "Black-owned culture brand. The PHRHX Show. 100 mastered beats. $79 Vault. $10K Rap Challenge.",
    // images omitted — falls back to the OG image generated by the
    // file-based convention above.
  },
};

// JSON-LD: Organization + WebSite schemas for AI engines + Knowledge Graph.
const STRUCTURED_DATA = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": "https://www.sneakzandbeatz.com/#organization",
      name: "Sneakz & Beatz",
      legalName: "Sneakz & Beatz LLC",
      url: "https://www.sneakzandbeatz.com",
      logo: "https://www.sneakzandbeatz.com/logo-mark-512.png",
      description:
        "Black-owned editorial brand for sneakerheads who live hip-hop, anime, and gaming. Operator of The PHRHX Show, the 100-beat catalog, and the $10K Rap Challenge.",
      // sameAs pulls from the canonical SOCIAL source-of-truth so AI engines
      // get the same handles as the footer. Don't hardcode strings here.
      sameAs: [
        SOCIAL.instagram.url,
        SOCIAL.tiktok.url,
        SOCIAL.x.url,
        SOCIAL.youtube.url,
        SOCIAL.substack.url,
      ],
      foundingDate: "2026-04-23",
      founder: {
        "@type": "Person",
        "@id": "https://www.sneakzandbeatz.com/#phrhx",
        name: "PHRHX",
        givenName: "Raymond",
        familyName: "Miller",
        jobTitle: "Founder, Host, Producer",
        url: "https://www.sneakzandbeatz.com/about",
      },
      address: {
        "@type": "PostalAddress",
        addressLocality: "San Diego",
        addressRegion: "CA",
        addressCountry: "US",
      },
    },
    {
      "@type": "WebSite",
      "@id": "https://www.sneakzandbeatz.com/#website",
      url: "https://www.sneakzandbeatz.com",
      name: "Sneakz & Beatz",
      publisher: { "@id": "https://www.sneakzandbeatz.com/#organization" },
      // SearchAction intentionally omitted — Sneakz & Beatz does not run a
      // unified site search. The Lane is editorial; the drops feed links out;
      // beats has its own filtering UI. Adding a SearchAction back without a
      // real search endpoint is worse than leaving it off.
    },
    {
      "@type": "PodcastSeries",
      "@id": "https://www.sneakzandbeatz.com/#podcast",
      name: "The PHRHX Show",
      description:
        "Hip-hop culture podcast covering sneakers, hip-hop, anime, and gaming through a Black-culture-first lens. Hosted by PHRHX.",
      url: "https://www.sneakzandbeatz.com/show",
      author: { "@id": "https://www.sneakzandbeatz.com/#phrhx" },
      publisher: { "@id": "https://www.sneakzandbeatz.com/#organization" },
    },
  ],
};

export default async function HomePage() {
  // "Shop × Channel" composition (2026-06 redesign). One room, one customer:
  // broadcast spine (OnAir + ProgramGuide) over boutique zones (RoomHero,
  // TheFeed, BeatLab, Merch, S&B Girls). All sections read from the same
  // systems as before — SOC drops engine, YouTube RSS, Stripe, merch.ts.
  //
  // Latest articles rail: always surfaces the newest published essays
  // (getLiveEssays is newest-first by goLiveAt). Per global rule the homepage
  // must always show the latest — the daily rebuild keeps this current.
  const latest = getLiveEssays().slice(0, 6);
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(STRUCTURED_DATA) }}
      />
      <OnAirBar />
      <Header />
      <RoomHero />
      <ProgramGuide />

      {/* Latest from The Lane — auto-updating; always the newest articles. */}
      {latest.length > 0 && (
        <section className="container" style={{ padding: "36px 0" }}>
          <div
            style={{
              display: "flex",
              alignItems: "baseline",
              justifyContent: "space-between",
              gap: 12,
              flexWrap: "wrap",
              marginBottom: 18,
            }}
          >
            <h2 style={{ margin: 0, fontSize: "1.6rem", fontWeight: 800 }}>
              Latest from The Lane
            </h2>
            <Link href="/the-lane" style={{ fontSize: "0.9rem", opacity: 0.8 }}>
              View all &rarr;
            </Link>
          </div>
          <div
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))",
              gap: 16,
            }}
          >
            {latest.map((e) => (
              <Link
                key={e.slug}
                href={`/the-lane/${e.slug}`}
                style={{
                  display: "block",
                  border: "1px solid var(--rule, #2a2a30)",
                  borderRadius: 12,
                  overflow: "hidden",
                  textDecoration: "none",
                  color: "inherit",
                  background: "var(--card, #111)",
                }}
              >
                <div style={{ height: 6, background: `#${e.ogAccent}` }} />
                <div style={{ padding: 16 }}>
                  <span
                    style={{
                      fontSize: "0.68rem",
                      letterSpacing: "0.12em",
                      textTransform: "uppercase",
                      fontWeight: 800,
                      opacity: 0.7,
                    }}
                  >
                    {e.pillar === "hiphop"
                      ? "Hip-Hop"
                      : e.pillar
                      ? e.pillar.charAt(0).toUpperCase() + e.pillar.slice(1)
                      : "The Lane"}
                  </span>
                  <h3 style={{ margin: "8px 0 6px", fontSize: "1.05rem", lineHeight: 1.25 }}>
                    {e.title}
                  </h3>
                  <p style={{ margin: 0, fontSize: "0.9rem", opacity: 0.75, lineHeight: 1.4 }}>
                    {e.subhead}
                  </p>
                </div>
              </Link>
            ))}
          </div>
        </section>
      )}

      <ShowEmbed />
      <BeatLabV3 />
      <MerchZone />
      <GirlsZone />
      <TikTokFeed />
      <AdBreak />
      <SubstackSticker />
      <Footer />
    </>
  );
}
