import Header from "@/components/Header";
import Hero from "@/components/Hero";
import RapChallengeBanner from "@/components/RapChallengeBanner";
import TrendingTicker from "@/components/TrendingTicker";
import DropsFeed from "@/components/DropsFeed";
import FeaturedStory from "@/components/FeaturedStory";
import FeaturedLaneEssay from "@/components/FeaturedLaneEssay";
import BrandPhotos from "@/components/BrandPhotos";
import TikTokFeed from "@/components/TikTokFeed";
import CreatorsCTA from "@/components/CreatorsCTA";
import PHRHXShow from "@/components/PHRHXShow";
import BeatStore from "@/components/BeatStore";
import SubstackSticker from "@/components/SubstackSticker";
import Footer from "@/components/Footer";
import { fetchTrending } from "@/lib/soc-engine";
import { SOCIAL } from "@/data/social";

// Use `title.absolute` so the layout's "%s — Sneakz & Beatz" template doesn't
// append a duplicate brand suffix to the homepage title.
export const metadata = {
  title: {
    absolute:
      "Sneakz & Beatz — Sneakers, Hip-Hop, Anime, Gaming. Black-owned culture brand.",
  },
  description:
    "Sneakz & Beatz is the editorial home for sneakerheads who live hip-hop, anime, and gaming. The PHRHX Show, 96 mastered beats, the $79 Vault, the $10K Rap Challenge.",
  alternates: { canonical: "https://www.sneakzandbeatz.com" },
  openGraph: {
    title: "Sneakz & Beatz — Sneakers, Hip-Hop, Anime, Gaming",
    description:
      "Black-owned culture brand for sneakerheads who live hip-hop, anime, and gaming. Watch The PHRHX Show, get 96 mastered beats in the $79 Vault, win $10K in the Rap Challenge.",
    url: "https://www.sneakzandbeatz.com",
    siteName: "Sneakz & Beatz",
    type: "website",
    // images omitted — file-based src/app/opengraph-image.tsx generates a
    // custom homepage OG card. Twitter inherits the same image.
  },
  twitter: {
    card: "summary_large_image",
    title: "Sneakz & Beatz — Sneakers, Hip-Hop, Anime, Gaming",
    description:
      "Black-owned culture brand. The PHRHX Show. 96 mastered beats. $79 Vault. $10K Rap Challenge.",
    // images omitted — falls back to the OG image generated by the
    // file-based convention above.
  },
};

// JSON-LD: Organization + WebSite schemas for AI engines + Knowledge Graph.
const STRUCTURED_DATA = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": "https://www.sneakzandbeatz.com/#organization",
      name: "Sneakz & Beatz",
      legalName: "Sneakz & Beatz LLC",
      url: "https://www.sneakzandbeatz.com",
      logo: "https://www.sneakzandbeatz.com/logo-mark-512.png",
      description:
        "Black-owned editorial brand for sneakerheads who live hip-hop, anime, and gaming. Operator of The PHRHX Show, the 96-beat catalog, and the $10K Rap Challenge.",
      // sameAs pulls from the canonical SOCIAL source-of-truth so AI engines
      // get the same handles as the footer. Don't hardcode strings here.
      sameAs: [
        SOCIAL.instagram.url,
        SOCIAL.tiktok.url,
        SOCIAL.x.url,
        SOCIAL.youtube.url,
        SOCIAL.substack.url,
      ],
      foundingDate: "2026-04-23",
      founder: {
        "@type": "Person",
        "@id": "https://www.sneakzandbeatz.com/#phrhx",
        name: "PHRHX",
        givenName: "Raymond",
        familyName: "Miller",
        jobTitle: "Founder, Host, Producer",
        url: "https://www.sneakzandbeatz.com/about",
      },
      address: {
        "@type": "PostalAddress",
        addressLocality: "San Diego",
        addressRegion: "CA",
        addressCountry: "US",
      },
    },
    {
      "@type": "WebSite",
      "@id": "https://www.sneakzandbeatz.com/#website",
      url: "https://www.sneakzandbeatz.com",
      name: "Sneakz & Beatz",
      publisher: { "@id": "https://www.sneakzandbeatz.com/#organization" },
      // SearchAction intentionally omitted — Sneakz & Beatz does not run a
      // unified site search. The Lane is editorial; the drops feed links out;
      // beats has its own filtering UI. Adding a SearchAction back without a
      // real search endpoint is worse than leaving it off.
    },
    {
      "@type": "PodcastSeries",
      "@id": "https://www.sneakzandbeatz.com/#podcast",
      name: "The PHRHX Show",
      description:
        "Hip-hop culture podcast covering sneakers, hip-hop, anime, and gaming through a Black-culture-first lens. Hosted by PHRHX.",
      url: "https://www.sneakzandbeatz.com/show",
      author: { "@id": "https://www.sneakzandbeatz.com/#phrhx" },
      publisher: { "@id": "https://www.sneakzandbeatz.com/#organization" },
    },
  ],
};

export default async function HomePage() {
  // Server-side fetch from the SOC engine. Falls back to defaults if engine is offline.
  const trending = await fetchTrending();

  // Reordered for culture-media positioning (post-ChatGPT-audit, 2026-06-04):
  // editorial signals first (ticker + drops + featured Lane essay + featured
  // story + show), THEN newsletter, THEN commerce (Beat Store + Rap Challenge),
  // THEN brand/community surfaces (photos + TikTok + S&B Girls), THEN footer.
  // The shift: first impression now reads "culture media that owns a beat
  // label" instead of "beat producer with a culture website."
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(STRUCTURED_DATA) }}
      />
      <Header />
      <Hero />

      {/* Editorial above the fold — what we cover, before what we sell. */}
      <TrendingTicker items={trending} />
      <DropsFeed
        title="What's dropping"
        subtitle="Sneakers leads. Then music, anime, and gaming. Tap any card — we link out to the source. No fluff, no rewrites, just the culture refresh."
      />
      <FeaturedLaneEssay />
      <FeaturedStory />

      {/* Audience flywheel — the show + newsletter. */}
      <PHRHXShow />
      <SubstackSticker />

      {/* Commerce — beats first, then the rap challenge. Both behind the
          editorial proof points. */}
      <BeatStore />
      <RapChallengeBanner />

      {/* Brand + community — photos, TikTok, the S&B Girls ambassador
          program lives near the bottom now per the audit (was up front;
          reads too forward for a brand still building audience). */}
      <BrandPhotos />
      <TikTokFeed />
      <CreatorsCTA />

      <Footer />
    </>
  );
}
