import type { MetadataRoute } from "next";

/**
 * robots.txt — generated by Next.js.
 *
 * Allow every crawler, including AI engines (GPTBot, ClaudeBot,
 * PerplexityBot, Google-Extended, etc.) so Sneakz & Beatz shows up in
 * both classic search and AI answers. Points crawlers at the sitemap.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [{ userAgent: "*", allow: "/" }],
    sitemap: "https://www.sneakzandbeatz.com/sitemap.xml",
    host: "https://www.sneakzandbeatz.com",
  };
}
