import Link from "next/link";
import { notFound } from "next/navigation";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { getEssay, getAllEssaySlugs, getLiveEssays } from "@/data/lane-essays";
import { renderMarkdown } from "@/lib/render-md";
import { jsonLd, articleSchema, phrhxPerson, breadcrumbList } from "@/lib/schema";
import fs from "node:fs";
import path from "node:path";

const SITE = "https://www.sneakzandbeatz.com";

// Auto-hero: if an image named after the slug sits in /public/lane, use it.
// Lets the owner add a real hero by just dropping <slug>.jpg in public/lane/
// — no code edits. Falls back to the branded banner when absent.
const LANE_IMG_DIR = path.join(process.cwd(), "public", "lane");
function findHeroFile(slug: string): string | null {
  for (const ext of ["jpg", "jpeg", "png", "webp"]) {
    if (fs.existsSync(path.join(LANE_IMG_DIR, `${slug}.${ext}`))) {
      return `/lane/${slug}.${ext}`;
    }
  }
  return null;
}

export async function generateStaticParams() {
  return getAllEssaySlugs();
}

export const dynamicParams = false;

type Params = { slug: string };

export async function generateMetadata({
  params,
}: {
  params: Promise<Params>;
}) {
  const { slug } = await params;
  const essay = getEssay(slug);
  if (!essay) return { title: "Lane essay not found" };

  return {
    title: essay.title,
    description: essay.description,
    keywords: essay.keywords,
    alternates: { canonical: `/the-lane/${essay.slug}` },
    openGraph: {
      title: `${essay.title} — Sneakz & Beatz`,
      description: essay.description,
      url: `${SITE}/the-lane/${essay.slug}`,
      type: "article",
      publishedTime: essay.publishedAt,
      modifiedTime: essay.modifiedAt || essay.publishedAt,
      authors: [`${SITE}/about`],
      tags: essay.keywords,
      // Per-essay OG image is generated by the colocated opengraph-image.tsx.
    },
  };
}

export default async function LaneEssayPage({
  params,
}: {
  params: Promise<Params>;
}) {
  const { slug } = await params;
  const essay = getEssay(slug);
  if (!essay) notFound();

  // Other essays for the cross-link rail at the bottom (live only).
  const others = getLiveEssays().filter((e) => e.slug !== essay.slug);

  return (
    <>
      {/* JSON-LD: Article + Person (PHRHX as author). The Person reference
          is included so AI engines see the author entity reinforced on
          every Lane essay. */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={jsonLd(
          articleSchema({
            url: `${SITE}/the-lane/${essay.slug}`,
            headline: essay.title,
            description: essay.description,
            datePublished: essay.publishedAt,
            dateModified: essay.modifiedAt || essay.publishedAt,
            keywords: essay.keywords,
          }),
        )}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={jsonLd(phrhxPerson())}
      />
      {/* BreadcrumbList — Home > The Lane > {essay} */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={jsonLd(
          breadcrumbList([
            { name: "Home", url: SITE },
            { name: "The Lane", url: `${SITE}/the-lane` },
            { name: essay.title, url: `${SITE}/the-lane/${essay.slug}` },
          ]),
        )}
      />

      <Header />

      <main className="container legal-page">
        <header className="legal-hero">
          <span className="eyebrow">The Lane · Essay</span>
          <h1 className="legal-title" style={{ whiteSpace: "pre-line" }}>
            {essay.headline}
          </h1>
          <p className="lead legal-lead">{essay.subhead}</p>
          <p
            className="legal-foot"
            style={{ marginTop: 18, opacity: 0.7, fontSize: "0.9rem" }}
          >
            By <Link href="/about">PHRHX</Link> · Published{" "}
            {new Date(essay.publishedAt).toLocaleDateString("en-US", {
              year: "numeric",
              month: "long",
              day: "numeric",
            })}
          </p>
          {(() => {
            const heroSrc = essay.heroImage ?? findHeroFile(essay.slug);
            if (heroSrc) {
              return (
                <figure style={{ margin: "24px 0 0" }}>
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img
                    src={heroSrc}
                    alt={essay.title}
                    style={{ width: "100%", borderRadius: 12, display: "block" }}
                  />
                  {essay.heroCredit && (
                    <figcaption style={{ fontSize: "0.78rem", opacity: 0.6, marginTop: 8 }}>
                      Photo:{" "}
                      {essay.heroCreditUrl ? (
                        <a href={essay.heroCreditUrl} target="_blank" rel="noopener noreferrer">
                          {essay.heroCredit}
                        </a>
                      ) : (
                        essay.heroCredit
                      )}
                    </figcaption>
                  )}
                </figure>
              );
            }
            return (
              <div
                style={{
                  margin: "24px 0 0",
                  minHeight: 220,
                  borderRadius: 12,
                  background: `radial-gradient(120% 140% at 100% 0%, #${essay.ogAccent} 0%, rgba(10,10,10,0.15) 55%), #0a0a0a`,
                  position: "relative",
                  overflow: "hidden",
                  display: "flex",
                  alignItems: "flex-end",
                  padding: 22,
                }}
              >
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src="/logo-mark-512.png"
                  alt=""
                  aria-hidden
                  style={{ position: "absolute", right: -24, top: -24, width: 210, opacity: 0.12 }}
                />
                <span
                  style={{
                    position: "relative",
                    fontSize: "0.72rem",
                    letterSpacing: "0.14em",
                    textTransform: "uppercase",
                    color: "rgba(255,255,255,0.9)",
                    fontWeight: 800,
                  }}
                >
                  {essay.pillar === "hiphop"
                    ? "Hip-Hop"
                    : essay.pillar
                    ? essay.pillar.charAt(0).toUpperCase() + essay.pillar.slice(1)
                    : "The Lane"}{" "}
                  · Sneakz &amp; Beatz
                </span>
              </div>
            );
          })()}
        </header>

        <article className="legal-section lane-essay-body">
          {renderMarkdown(essay.body)}
        </article>

        {/* Cross-link rail to the other essays — gives readers a path through
            the corpus and gives AI engines internal entity reinforcement. */}
        {others.length > 0 && (
          <section className="legal-section">
            <h2>More from The Lane</h2>
            <ul>
              {others.map((e) => (
                <li key={e.slug}>
                  <Link href={`/the-lane/${e.slug}`}>
                    <strong>{e.title}</strong>
                  </Link>
                  {" — "}
                  {e.subhead}
                </li>
              ))}
              <li>
                <Link href="/the-lane">
                  <strong>The Lane — positioning essay</strong>
                </Link>
                {" — "}
                Why Sneakz & Beatz exists and where it sits.
              </li>
            </ul>
          </section>
        )}

        <p className="legal-foot">
          <Link href="/the-lane">← Back to The Lane</Link> ·{" "}
          <Link href="/about">About PHRHX</Link> ·{" "}
          <Link href="/show">The PHRHX Show</Link> ·{" "}
          <Link href="/beats">Beat Store</Link> ·{" "}
          <Link href="/rap-challenge">$10K Rap Challenge</Link>
        </p>
      </main>

      <Footer />
    </>
  );
}
