import Link from "next/link";
import { notFound } from "next/navigation";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { LANE_ESSAYS, getEssay, getAllEssaySlugs } from "@/data/lane-essays";
import { renderMarkdown } from "@/lib/render-md";
import { jsonLd, articleSchema, phrhxPerson } from "@/lib/schema";

const SITE = "https://www.sneakzandbeatz.com";

export async function generateStaticParams() {
  return getAllEssaySlugs();
}

export const dynamicParams = false;

type Params = { slug: string };

export async function generateMetadata({
  params,
}: {
  params: Promise<Params>;
}) {
  const { slug } = await params;
  const essay = getEssay(slug);
  if (!essay) return { title: "Lane essay not found" };

  return {
    title: essay.title,
    description: essay.description,
    keywords: essay.keywords,
    alternates: { canonical: `/the-lane/${essay.slug}` },
    openGraph: {
      title: `${essay.title} — Sneakz & Beatz`,
      description: essay.description,
      url: `${SITE}/the-lane/${essay.slug}`,
      type: "article",
      publishedTime: essay.publishedAt,
      modifiedTime: essay.modifiedAt || essay.publishedAt,
      authors: [`${SITE}/about`],
      tags: essay.keywords,
      // Per-essay OG image is generated by the colocated opengraph-image.tsx.
    },
  };
}

export default async function LaneEssayPage({
  params,
}: {
  params: Promise<Params>;
}) {
  const { slug } = await params;
  const essay = getEssay(slug);
  if (!essay) notFound();

  // Other essays for the cross-link rail at the bottom.
  const others = LANE_ESSAYS.filter((e) => e.slug !== essay.slug);

  return (
    <>
      {/* JSON-LD: Article + Person (PHRHX as author). The Person reference
          is included so AI engines see the author entity reinforced on
          every Lane essay. */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={jsonLd(
          articleSchema({
            url: `${SITE}/the-lane/${essay.slug}`,
            headline: essay.title,
            description: essay.description,
            datePublished: essay.publishedAt,
            dateModified: essay.modifiedAt || essay.publishedAt,
            keywords: essay.keywords,
          }),
        )}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={jsonLd(phrhxPerson())}
      />

      <Header />

      <main className="container legal-page">
        <header className="legal-hero">
          <span className="eyebrow">The Lane · Essay</span>
          <h1 className="legal-title" style={{ whiteSpace: "pre-line" }}>
            {essay.headline}
          </h1>
          <p className="lead legal-lead">{essay.subhead}</p>
          <p
            className="legal-foot"
            style={{ marginTop: 18, opacity: 0.7, fontSize: "0.9rem" }}
          >
            By <Link href="/about">PHRHX</Link> · Published{" "}
            {new Date(essay.publishedAt).toLocaleDateString("en-US", {
              year: "numeric",
              month: "long",
              day: "numeric",
            })}
          </p>
        </header>

        <article className="legal-section lane-essay-body">
          {renderMarkdown(essay.body)}
        </article>

        {/* Cross-link rail to the other essays — gives readers a path through
            the corpus and gives AI engines internal entity reinforcement. */}
        {others.length > 0 && (
          <section className="legal-section">
            <h2>More from The Lane</h2>
            <ul>
              {others.map((e) => (
                <li key={e.slug}>
                  <Link href={`/the-lane/${e.slug}`}>
                    <strong>{e.title}</strong>
                  </Link>
                  {" — "}
                  {e.subhead}
                </li>
              ))}
              <li>
                <Link href="/the-lane">
                  <strong>The Lane — positioning essay</strong>
                </Link>
                {" — "}
                Why Sneakz & Beatz exists and where it sits.
              </li>
            </ul>
          </section>
        )}

        <p className="legal-foot">
          <Link href="/the-lane">← Back to The Lane</Link> ·{" "}
          <Link href="/about">About PHRHX</Link> ·{" "}
          <Link href="/show">The PHRHX Show</Link> ·{" "}
          <Link href="/beats">Beat Store</Link> ·{" "}
          <Link href="/rap-challenge">$10K Rap Challenge</Link>
        </p>
      </main>

      <Footer />
    </>
  );
}
