import type { YouTubeVideo } from "@/lib/youtube";

// Auto-generated by REFRESH_SHOW_VIDEOS.command from the channel RSS.
// Your Mac reaches YouTube even when Vercel's build-time fetch is blocked,
// so this is the real latest list. Re-run the command to refresh.
export const FALLBACK_VIDEOS: YouTubeVideo[] = [
  {
    "id": "R79eHfPUN8c",
    "title": "Will the Sony Boycott Hurt Spider-Man: Brand New Day? #shorts #spiderman",
    "url": "https://www.youtube.com/watch?v=R79eHfPUN8c",
    "publishedAt": "2026-07-25T00:27:59+00:00",
    "thumbnail": "https://i.ytimg.com/vi/R79eHfPUN8c/hqdefault.jpg",
    "thumbnailHigh": "https://i.ytimg.com/vi/R79eHfPUN8c/maxresdefault.jpg",
    "embedUrl": "https://www.youtube.com/embed/R79eHfPUN8c"
  },
  {
    "id": "Gk3CxF6oK30",
    "title": "Custom Olive Green Jordan 6s Made for Sneakz & Beatz \ud83d\udd25",
    "url": "https://www.youtube.com/watch?v=Gk3CxF6oK30",
    "publishedAt": "2026-07-24T02:44:33+00:00",
    "thumbnail": "https://i.ytimg.com/vi/Gk3CxF6oK30/hqdefault.jpg",
    "thumbnailHigh": "https://i.ytimg.com/vi/Gk3CxF6oK30/maxresdefault.jpg",
    "embedUrl": "https://www.youtube.com/embed/Gk3CxF6oK30"
  },
  {
    "id": "CvfpnqxSywo",
    "title": "Air Jordan 8 \u201cBIN 23\u201d Is Looking CRAZY \ud83d\udd25 #shorts",
    "url": "https://www.youtube.com/watch?v=CvfpnqxSywo",
    "publishedAt": "2026-07-24T01:09:41+00:00",
    "thumbnail": "https://i.ytimg.com/vi/CvfpnqxSywo/hqdefault.jpg",
    "thumbnailHigh": "https://i.ytimg.com/vi/CvfpnqxSywo/maxresdefault.jpg",
    "embedUrl": "https://www.youtube.com/embed/CvfpnqxSywo"
  },
  {
    "id": "pO1Sj-OnXGc",
    "title": "True Blue Jordan 3s Secured\u2026 My Pair Is On the Way \ud83d\udc40\ud83d\udd25 #shorts",
    "url": "https://www.youtube.com/watch?v=pO1Sj-OnXGc",
    "publishedAt": "2026-07-23T22:04:27+00:00",
    "thumbnail": "https://i.ytimg.com/vi/pO1Sj-OnXGc/hqdefault.jpg",
    "thumbnailHigh": "https://i.ytimg.com/vi/pO1Sj-OnXGc/maxresdefault.jpg",
    "embedUrl": "https://www.youtube.com/embed/pO1Sj-OnXGc"
  },
  {
    "id": "GaTPbZChnvA",
    "title": "Olive Green Jordan 6s, custom made for Sneakz & Beatz \ud83e\uded2\ud83d\udd25#shorts",
    "url": "https://www.youtube.com/watch?v=GaTPbZChnvA",
    "publishedAt": "2026-07-23T19:04:17+00:00",
    "thumbnail": "https://i.ytimg.com/vi/GaTPbZChnvA/hqdefault.jpg",
    "thumbnailHigh": "https://i.ytimg.com/vi/GaTPbZChnvA/maxresdefault.jpg",
    "embedUrl": "https://www.youtube.com/embed/GaTPbZChnvA"
  },
  {
    "id": "uMlXrLzVzQI",
    "title": "Avengers: Doomsday Trailer Looking FIRE\u2026 Is Marvel Back? \ud83d\udd25#shorts",
    "url": "https://www.youtube.com/watch?v=uMlXrLzVzQI",
    "publishedAt": "2026-07-23T15:13:54+00:00",
    "thumbnail": "https://i.ytimg.com/vi/uMlXrLzVzQI/hqdefault.jpg",
    "thumbnailHigh": "https://i.ytimg.com/vi/uMlXrLzVzQI/maxresdefault.jpg",
    "embedUrl": "https://www.youtube.com/embed/uMlXrLzVzQI"
  },
  {
    "id": "-tY0gBsLy8g",
    "title": "FUTURE DROPS NEW ALBUM, BANNED JORDANS THAT ONLY GOT HOTTER, BLACK CLOVER RETURNS | THE PHRHX SHOW",
    "url": "https://www.youtube.com/watch?v=-tY0gBsLy8g",
    "publishedAt": "2026-06-16T21:20:08+00:00",
    "thumbnail": "https://i.ytimg.com/vi/-tY0gBsLy8g/hqdefault.jpg",
    "thumbnailHigh": "https://i.ytimg.com/vi/-tY0gBsLy8g/maxresdefault.jpg",
    "embedUrl": "https://www.youtube.com/embed/-tY0gBsLy8g"
  },
  {
    "id": "u_Lp4mOdHV0",
    "title": "Jay-Z Responds to Drake, State of Play Recap, & Toro 4s",
    "url": "https://www.youtube.com/watch?v=u_Lp4mOdHV0",
    "publishedAt": "2026-06-03T17:51:29+00:00",
    "thumbnail": "https://i.ytimg.com/vi/u_Lp4mOdHV0/hqdefault.jpg",
    "thumbnailHigh": "https://i.ytimg.com/vi/u_Lp4mOdHV0/maxresdefault.jpg",
    "embedUrl": "https://www.youtube.com/embed/u_Lp4mOdHV0"
  },
  {
    "id": "2SBnn0bY2xY",
    "title": "The New BRMG!",
    "url": "https://www.youtube.com/watch?v=2SBnn0bY2xY",
    "publishedAt": "2026-05-01T19:28:59+00:00",
    "thumbnail": "https://i.ytimg.com/vi/2SBnn0bY2xY/hqdefault.jpg",
    "thumbnailHigh": "https://i.ytimg.com/vi/2SBnn0bY2xY/maxresdefault.jpg",
    "embedUrl": "https://www.youtube.com/embed/2SBnn0bY2xY"
  },
  {
    "id": "MpvEDKUeNes",
    "title": "Rap's BIGGEST Flop Stars of 2025!",
    "url": "https://www.youtube.com/watch?v=MpvEDKUeNes",
    "publishedAt": "2025-01-16T05:18:31+00:00",
    "thumbnail": "https://i.ytimg.com/vi/MpvEDKUeNes/hqdefault.jpg",
    "thumbnailHigh": "https://i.ytimg.com/vi/MpvEDKUeNes/maxresdefault.jpg",
    "embedUrl": "https://www.youtube.com/embed/MpvEDKUeNes"
  }
];
